### ISSUE TITLE
1.0.0 Release Checklist

### ISSUE THREAD

**Issue by garetmckinley** [garetmckinley/hedron#80]
## `LayoutProvider`

- [x] allow custom debug fill colors/outlines to be set on `LayoutProvider`.
  - Ideal API: `<LayoutProvider debug={{ enabled: true, outline: 'solid 10px green', fill: 'blue' }}>`
  - Notes: 
    - Debug fills need to always be have an alpha of `.15`, even when a solid color is passed in.
    - The alpha **cannot** be set using `opacity: .15`, this would cause the contents to appear transparent, only the background color should be affected.
    - The ideal way to handle this, would be to extract the individual rgb channels from the input hex and generate a custom `rgba()` with a `.15` alpha set.

## `Container`

- [ ] allow `100%` height in Safari
  - This seems like it should be logical enough, but Safari doesn't allow `height: 100%` to be set on an element unless the parent has an absolute height set. There are a few workaround to this including using `position: absolute` on the `height: 100%` element with `position: relative` on the parent element. But this is less than ideal and will break most of the other layout features, requiring a massive re-write. Need to find another solution.
- [ ] `direction` should accept either a `string` or `object`
  - this should use the same methods as other props like `width`/`height`, allowing the direction to be changed based on the active breakpoint.
- [ ] `alignX`/`alignY` should accept either a `string` or `object`
   - this should use the same methods as other props like `width`/`height`, allowing the alignment on both axes to be changed based on the active breakpoint.

## `flowtype`

- [ ] add flow annotations to `breakpoint` utility

### `Section`

- [ ] add a story for `height`
- [ ] add a story for `width`
- [ ] add a story for `positioning` (this should demonstrate the `absolute`, `top`, `bottom`, `left`, and `right` props)

### `Container`

- [ ] add a story for `height`
- [ ] add a story for `width`
- [ ] add a story for `grow`
- [ ] add a story for `shrink`
- [ ] add a story for `flex`
- [x] add a story for `wrap`
- [x] add a story for `direction`

### `Box`

- [ ] add a story for `height`
- [x] add a story for `width`
- [x] add a story for `shift`
- [x] add a story for `grow`
- [ ] add a story for `shrink`
- [ ] add a story for `flex`
- [ ] add a story for `fluid`

## pre-production

- [ ] remove all unused/legacy code
- [ ] ensure all variables and class names are relevant
- [ ] finalize the all component property names **(these cannot be changed after `1.0.0` is published)**

## Contributing

If you wish to help on any of these items, please drop a comment down below letting me know what you're working on. This will ensure that two people aren't simultaneously working on the same thing. Thanks!

**Comment by brukh** [comment]
Working on updating the `LayoutProvider` debug options 😎

**Comment by garetmckinley** [comment]
I'm currently pulling my hair out trying to fix the safari issues 😎 

![c4jt321](https://cloud.githubusercontent.com/assets/1624279/26767150/1da23612-496b-11e7-88a5-46db7ba237b9.png)

**Comment by brukh** [comment]
Adding flowtype and section docs 💻
